"""Add semantic layer tables

Revision ID: 831fdf55444c
Revises: 2c658ddd5087
Create Date: 2026-01-07 17:59:37.140382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '831fdf55444c'
down_revision: Union[str, None] = '2c658ddd5087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_entities',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plural_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_table', sa.String(length=255), nullable=False),
    sa.Column('sql_definition', sa.Text(), nullable=True),
    sa.Column('is_certified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_semantic_entities_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_entities'))
    )
    op.create_index(op.f('ix_semantic_entities_is_certified'), 'semantic_entities', ['is_certified'], unique=False)
    op.create_index(op.f('ix_semantic_entities_name'), 'semantic_entities', ['name'], unique=False)
    op.create_index(op.f('ix_semantic_entities_owner_id'), 'semantic_entities', ['owner_id'], unique=False)
    op.create_table('semantic_dimensions',
    sa.Column('semantic_entity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sql_column', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('display_format', sa.String(length=100), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['semantic_entity_id'], ['semantic_entities.id'], name=op.f('fk_semantic_dimensions_semantic_entity_id_semantic_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_dimensions'))
    )
    op.create_index(op.f('ix_semantic_dimensions_name'), 'semantic_dimensions', ['name'], unique=False)
    op.create_index(op.f('ix_semantic_dimensions_semantic_entity_id'), 'semantic_dimensions', ['semantic_entity_id'], unique=False)
    op.create_table('semantic_measures',
    sa.Column('semantic_entity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('calculation_type', sa.String(length=50), server_default='aggregation', nullable=False),
    sa.Column('aggregation_function', sa.String(length=20), nullable=False),
    sa.Column('base_column', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=100), nullable=True),
    sa.Column('default_format_pattern', sa.String(length=100), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['semantic_entity_id'], ['semantic_entities.id'], name=op.f('fk_semantic_measures_semantic_entity_id_semantic_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_measures'))
    )
    op.create_index(op.f('ix_semantic_measures_name'), 'semantic_measures', ['name'], unique=False)
    op.create_index(op.f('ix_semantic_measures_semantic_entity_id'), 'semantic_measures', ['semantic_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_measures_semantic_entity_id'), table_name='semantic_measures')
    op.drop_index(op.f('ix_semantic_measures_name'), table_name='semantic_measures')
    op.drop_table('semantic_measures')
    op.drop_index(op.f('ix_semantic_dimensions_semantic_entity_id'), table_name='semantic_dimensions')
    op.drop_index(op.f('ix_semantic_dimensions_name'), table_name='semantic_dimensions')
    op.drop_table('semantic_dimensions')
    op.drop_index(op.f('ix_semantic_entities_owner_id'), table_name='semantic_entities')
    op.drop_index(op.f('ix_semantic_entities_name'), table_name='semantic_entities')
    op.drop_index(op.f('ix_semantic_entities_is_certified'), table_name='semantic_entities')
    op.drop_table('semantic_entities')
    # ### end Alembic commands ###
