"""add_query_history_table

Revision ID: 32df6e9fa0b6
Revises: 0ac961230897
Create Date: 2026-01-08 08:29:46.126949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32df6e9fa0b6'
down_revision: Union[str, None] = '0ac961230897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('query_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_query_history_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_history'))
    )
    op.create_index(op.f('ix_query_history_entity_id'), 'query_history', ['entity_id'], unique=False)
    op.create_index(op.f('ix_query_history_executed_at'), 'query_history', ['executed_at'], unique=False)
    op.create_index(op.f('ix_query_history_owner_id'), 'query_history', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_history_owner_id'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_executed_at'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_entity_id'), table_name='query_history')
    op.drop_table('query_history')
    # ### end Alembic commands ###
